### ISSUE TITLE
启动循环依赖问题

### ISSUE THREAD

**Issue by devhh** [fanpan26/tio-websocket-spring-boot-starter#3]

**Comment by devhh** [comment]
The dependencies of some of the beans in the application context form a cycle:

   org.tio.websocket.starter.TioWebSocketServerInitializerConfiguration (field private org.tio.websocket.starter.TioWebSocketServerBootstrap org.tio.websocket.starter.TioWebSocketServerInitializerConfiguration.webSocketServerBootstrap)
┌─────┐
|  org.tio.websocket.starter.TioWebSocketServerAutoConfiguration (field private org.tio.websocket.starter.TioWebSocketClassScanner org.tio.websocket.starter.TioWebSocketServerAutoConfiguration.tioWebSocketClassScanner)
└─────┘

**Comment by fanpan26** [comment]
> 

springboot 什么版本？

**Comment by devhh** [comment]
springboot-2.7.1

**Comment by fanpan26** [comment]
> springboot-2.7.1

版本较高，可能不支持，这个starter比较简单，可以copy到自己项目中去，自行修改。
